version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: install spacy models
          command: |
            . venv/bin/activate
            python3 -m spacy download en_core_web_sm

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir test_results
            pytest --junitxml=test_results/pytest/junit.xml

      - run:
          name: coverage
          command: |
            . venv/bin/activate
            coveralls

      - store_test_results:
          path: test_results

      - store_artifacts:
          path: test_results
