---
name: Python

"on":
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: venv
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      - name: Install spacy models
        run: |
          . venv/bin/activate
          python3 -m spacy download en_core_web_sm
      - name: Test with pytest
        run: |
          . venv/bin/activate
          mkdir test_results
          pytest --cov-report=xml --cov=urlshortener tests/